=== CODEGOWRISH/java-project-HR/src/gow/demo/hr/Employee_BasicData.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Employees (Employee*)>
<!ELEMENT Employee (name, dept, joindate)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dept (#PCDATA)>
<!ELEMENT joindate (#PCDATA)>

=== CODEGOWRISH/java-project-HR/src/gow/demo/hr/Employee_Data.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Employees SYSTEM "Employee_BasicData.dtd">
<Employees>
  <Employee>
    <name>Ramesh</name>
    <dept>DBA</dept>
    <joindate>01-01-2001</joindate>
  </Employee>
  <Employee>
    <name>Ramesh</name>
    <dept>UNIX</dept>
    <joindate>01-01-1991</joindate>
  </Employee>
  <Employee>
  	<name>Suresh</name>
  	<dept>NETWORKING</dept>
  	<joindate>01-01-1981</joindate>
  </Employee>
</Employees>
